const P = "packs/contrats/";

export default {
  id: "contrats",
  version: "2026.10.1",
  title: "Droit des contrats et des obligations",
  branch: "Droit privé",
  icon: "🤝",
  color: "#2c5b9a",
  order: 1,
  updatedAt: "2026-10-01",
  description: "La réforme de 2016 en profondeur : formation, contenu, effets, inexécution, clauses des contrats d'affaires, régime général, prescription et preuve.",
  modules: [
    {
      id: "formation",
      title: "La formation du contrat",
      level: 1,
      summary: "Principes directeurs, négociations et avant-contrats, consentement et vices, contenu du contrat, nullité et caducité.",
      lessons: [
        {
          id: "reforme-2016-principes",
          title: "La réforme de 2016 : nouveau plan, principes directeurs, droit transitoire",
          duration: 18,
          src: P + "reforme-2016-principes.md",
          objectives: ["Retrouver les correspondances ancien / nouveau Code", "Maîtriser les trois principes directeurs", "Déterminer le droit applicable à un contrat selon sa date"],
          keyRefs: ["Art. 1102 C. civ.", "Art. 1103 C. civ.", "Art. 1104 C. civ.", "Art. 1105 C. civ.", "Art. 1110 C. civ.", "Ord. n° 2016-131 du 10 févr. 2016", "L. n° 2018-287 du 20 avr. 2018"],
          quiz: [
            { type: "qcm", q: "À quel article figure désormais la bonne foi contractuelle ?", choices: ["1134", "1103", "1104", "1112"], answer: 2, explain: "Art. 1104 : négociation, formation et exécution de bonne foi ; disposition d'ordre public." },
            { type: "vf", q: "La cause reste l'une des conditions de validité du contrat.", answer: false, explain: "Art. 1128 : consentement, capacité, contenu licite et certain. La cause a disparu en tant que notion." },
            { type: "qcm", q: "Un contrat conclu le 15 septembre 2016 est régi par :", choices: ["Le droit issu de l'ordonnance", "L'ancien droit", "La loi de ratification", "Le juge choisit"], answer: 1, explain: "La réforme s'applique aux contrats conclus à compter du 1er octobre 2016." },
            { type: "qcm", q: "Le contrat d'adhésion est défini comme :", choices: ["Un contrat conclu avec un consommateur", "Un contrat comportant un ensemble de clauses non négociables, déterminées à l'avance par l'une des parties", "Un contrat-cadre", "Un contrat sans écrit"], answer: 1, explain: "Art. 1110, rédaction issue de la loi de ratification de 2018." },
            { type: "vf", q: "Les parties peuvent écarter par une clause l'exigence de bonne foi.", answer: false, explain: "L'art. 1104 est d'ordre public." },
            { type: "qcm", q: "Que décide l'arrêt Les Maréchaux (Cass. com., 10 juill. 2007) ?", choices: ["La bonne foi autorise le juge à réviser le prix", "La bonne foi sanctionne l'usage déloyal d'une prérogative sans atteindre la substance des droits et obligations", "La bonne foi ne concerne pas l'exécution", "Le juge peut créer de nouvelles obligations"], answer: 1, explain: "Arrêt de principe sur les limites de la bonne foi." },
          ],
          flashcards: [
            { q: "Ancien 1134 al. 1, 2, 3 → nouveaux articles ?", a: "1103 (force obligatoire), 1193 (révocation mutuelle), 1104 (bonne foi)." },
            { q: "Date d'entrée en vigueur de la réforme du droit des contrats ?", a: "1er octobre 2016 (ord. n° 2016-131 du 10 févr. 2016, ratifiée par la loi du 20 avr. 2018)." },
            { q: "Conditions de validité (art. 1128) ?", a: "Consentement des parties, capacité de contracter, contenu licite et certain." },
            { q: "Ancien 1147 et 1148 → ?", a: "1231-1 (responsabilité contractuelle) et 1218 (force majeure)." },
          ],
        },
        {
          id: "negociations-avant-contrats",
          title: "Négociations, offre et acceptation, pacte de préférence, promesse unilatérale",
          duration: 20,
          src: P + "negociations-avant-contrats.md",
          objectives: ["Mesurer la responsabilité pour rupture des pourparlers", "Appliquer le devoir précontractuel d'information", "Maîtriser pacte de préférence et promesse unilatérale"],
          keyRefs: ["Art. 1112 C. civ.", "Art. 1112-1 C. civ.", "Art. 1112-2 C. civ.", "Art. 1121 C. civ.", "Art. 1123 C. civ.", "Art. 1124 C. civ."],
          quiz: [
            { type: "qcm", q: "En cas de rupture fautive des pourparlers, peut-on obtenir réparation de la perte de chance de réaliser les gains attendus du contrat ?", choices: ["Oui, toujours", "Oui, si la faute est lourde", "Non (art. 1112 al. 2)", "Seulement entre commerçants"], answer: 2, explain: "Ni la perte des avantages attendus, ni la perte de chance de les obtenir (Manoukian, codifié et étendu en 2018)." },
            { type: "vf", q: "Le devoir précontractuel d'information porte sur l'estimation de la valeur de la prestation.", answer: false, explain: "Exclu expressément par l'art. 1112-1 (solution Baldus)." },
            { type: "qcm", q: "Le contrat entre absents est conclu :", choices: ["À l'émission de l'acceptation", "À la réception de l'acceptation par l'offrant", "À la signature du dernier écrit", "À l'exécution"], answer: 1, explain: "Art. 1121 : théorie de la réception." },
            { type: "qcm", q: "Le promettant d'une promesse unilatérale se rétracte pendant le délai d'option. Le bénéficiaire lève l'option :", choices: ["Le contrat n'est pas formé, dommages-intérêts seulement", "Le contrat promis est formé", "La promesse est nulle", "Le juge décide librement"], answer: 1, explain: "Art. 1124 al. 2 ; revirement Civ. 3e, 23 juin 2021 même pour les promesses antérieures." },
            { type: "qcm", q: "Pour obtenir la substitution dans un contrat conclu en violation d'un pacte de préférence, il faut prouver que le tiers connaissait :", choices: ["Le pacte seulement", "Le pacte et l'intention du bénéficiaire de s'en prévaloir", "Le prix proposé", "Rien, la substitution est automatique"], answer: 1, explain: "Art. 1123 al. 2, codifiant Cass. ch. mixte, 26 mai 2006." },
            { type: "vf", q: "Le devoir précontractuel d'information peut être exclu par une clause entre professionnels.", answer: false, explain: "Art. 1112-1 dernier al. : les parties ne peuvent ni le limiter ni l'exclure." },
          ],
          flashcards: [
            { q: "Préjudice réparable en cas de rupture fautive des pourparlers ?", a: "Frais engagés, atteinte à l'image… mais ni les avantages attendus du contrat, ni la perte de chance de les obtenir (art. 1112)." },
            { q: "Action interrogatoire du pacte de préférence ?", a: "Le tiers demande au bénéficiaire de confirmer l'existence du pacte et son intention ; silence dans un délai raisonnable = plus d'action en nullité/substitution (art. 1123 al. 3-4)." },
            { q: "Arrêt Cruz (1993) : sort ?", a: "Abandonné : art. 1124 (2016) et Civ. 3e, 23 juin 2021 — la rétractation du promettant n'empêche pas la formation." },
          ],
        },
        {
          id: "validite-consentement",
          title: "Le consentement et ses vices : erreur, dol, violence, abus de dépendance",
          duration: 20,
          src: P + "validite-consentement.md",
          objectives: ["Caractériser chaque vice du consentement", "Connaître la sanction et la prescription", "Appliquer la violence économique (art. 1143)"],
          keyRefs: ["Art. 1130 C. civ.", "Art. 1132 C. civ.", "Art. 1137 C. civ.", "Art. 1139 C. civ.", "Art. 1143 C. civ.", "Art. 1144 C. civ."],
          quiz: [
            { type: "qcm", q: "L'erreur provoquée par un dol :", choices: ["Doit être excusable", "Est toujours excusable", "Ne peut porter que sur les qualités essentielles", "N'est pas une cause de nullité"], answer: 1, explain: "Art. 1139 : toujours excusable, et cause de nullité même si elle porte sur la valeur ou un simple motif." },
            { type: "vf", q: "Le dol d'un tiers de connivence peut entraîner la nullité.", answer: true, explain: "Art. 1138 al. 2." },
            { type: "qcm", q: "La violence par abus de dépendance exige :", choices: ["Une dépendance économique quelconque", "Une dépendance à l'égard du cocontractant, un abus et un avantage manifestement excessif", "Une menace physique", "Une faute pénale"], answer: 1, explain: "Art. 1143, précisé par la loi de 2018 (« à son égard »)." },
            { type: "qcm", q: "Délai pour agir en nullité pour dol :", choices: ["2 ans à compter du contrat", "5 ans à compter de la découverte du dol", "10 ans", "30 ans"], answer: 1, explain: "Art. 1144 et 2224." },
            { type: "qcm", q: "L'arrêt Vilgrain (Cass. com., 27 févr. 1996) consacre :", choices: ["Le devoir de loyauté du dirigeant envers l'associé cédant", "La violence économique", "L'erreur sur la valeur", "La caducité"], answer: 0, explain: "Réticence dolosive du dirigeant acquéreur qui dissimule une revente plus avantageuse." },
            { type: "vf", q: "L'erreur sur la valeur résultant d'une appréciation économique inexacte est une cause de nullité.", answer: false, explain: "Art. 1136, sauf si elle est provoquée par un dol (art. 1139)." },
          ],
          flashcards: [
            { q: "Caractère déterminant d'un vice (art. 1130) ?", a: "Sans lui, la partie n'aurait pas contracté ou à des conditions substantiellement différentes ; apprécié selon les personnes et circonstances." },
            { q: "Dol : trois formes ?", a: "Manœuvres, mensonges, dissimulation intentionnelle d'une information déterminante (réticence) — art. 1137." },
            { q: "Arrêt Baldus ?", a: "Civ. 1re, 3 mai 2000 : pas d'obligation pour l'acheteur d'informer sur la valeur — codifié aux art. 1112-1 et 1137 al. 3." },
          ],
        },
        {
          id: "contenu-contrat",
          title: "Le contenu du contrat : prix, contrepartie, Chronopost, clauses abusives",
          duration: 20,
          src: P + "contenu-contrat.md",
          objectives: ["Savoir où sont passées les fonctions de la cause", "Maîtriser le prix unilatéral et son contrôle", "Appliquer les art. 1169, 1170 et 1171"],
          keyRefs: ["Art. 1162 C. civ.", "Art. 1164 C. civ.", "Art. 1165 C. civ.", "Art. 1168 C. civ.", "Art. 1169 C. civ.", "Art. 1170 C. civ.", "Art. 1171 C. civ."],
          quiz: [
            { type: "qcm", q: "Dans un contrat-cadre, le prix fixé unilatéralement de façon abusive peut entraîner :", choices: ["La nullité du contrat-cadre", "La fixation du prix par le juge", "Des dommages-intérêts et, le cas échéant, la résolution", "Rien"], answer: 2, explain: "Art. 1164, consacrant Ass. plén., 1er déc. 1995." },
            { type: "qcm", q: "La sanction de l'art. 1170 est :", choices: ["La nullité du contrat", "Le réputé non écrit de la clause", "La réduction du prix", "Des dommages-intérêts"], answer: 1, explain: "La clause qui prive de sa substance l'obligation essentielle est réputée non écrite." },
            { type: "vf", q: "L'art. 1171 permet de contrôler l'adéquation du prix à la prestation.", answer: false, explain: "Ni l'objet principal, ni l'adéquation du prix ne sont contrôlés." },
            { type: "qcm", q: "Une cession de parts à prix dérisoire sans autre contrepartie est :", choices: ["Valable", "Nulle (art. 1169)", "Réputée non écrite", "Rescindable pour lésion"], answer: 1, explain: "Contrepartie illusoire ou dérisoire : nullité." },
            { type: "qcm", q: "Faurecia (Cass. com., 29 juin 2010) précise que :", choices: ["Toute clause limitative est nulle", "Seule la clause qui contredit la portée de l'obligation essentielle est réputée non écrite", "Le plafond doit égaler le prix", "La faute lourde se déduit de l'obligation essentielle"], answer: 1, explain: "Un plafond non dérisoire reste valable." },
          ],
          flashcards: [
            { q: "Où sont passées les fonctions de la cause ?", a: "1162 (but illicite), 1169 (contrepartie illusoire ou dérisoire), 1170 (obligation essentielle), 1186 (caducité)." },
            { q: "Art. 1171 : conditions ?", a: "Contrat d'adhésion ; clause non négociable prédéterminée ; déséquilibre significatif ; hors objet principal et prix ; sanction : réputé non écrit." },
            { q: "Ass. plén., 1er déc. 1995 ?", a: "L'indétermination du prix dans un contrat-cadre n'en affecte pas la validité ; seul l'abus dans la fixation est sanctionné." },
          ],
        },
        {
          id: "nullite-caducite",
          title: "Nullité, restitutions et caducité",
          duration: 15,
          src: P + "nullite-caducite.md",
          objectives: ["Distinguer nullité absolue et relative", "Utiliser l'action interrogatoire", "Appliquer la caducité aux ensembles contractuels"],
          keyRefs: ["Art. 1179 C. civ.", "Art. 1182 C. civ.", "Art. 1183 C. civ.", "Art. 1184 C. civ.", "Art. 1186 C. civ.", "Art. 1352 C. civ."],
          quiz: [
            { type: "qcm", q: "Critère de distinction des nullités :", choices: ["La gravité du vice", "La finalité de la règle violée (intérêt général / privé)", "La qualité des parties", "Le montant"], answer: 1, explain: "Art. 1179 : théorie moderne." },
            { type: "qcm", q: "Délai de l'action interrogatoire en nullité (art. 1183) :", choices: ["1 mois", "2 mois", "6 mois", "1 an"], answer: 2, explain: "Six mois pour agir, à peine de forclusion." },
            { type: "vf", q: "La caducité d'un contrat interdépendant suppose que le cocontractant connaissait l'opération d'ensemble.", answer: true, explain: "Art. 1186 al. 3." },
            { type: "qcm", q: "La nullité relative peut être invoquée par :", choices: ["Toute personne intéressée", "Le ministère public", "La seule partie protégée", "Le juge d'office"], answer: 2, explain: "Art. 1181." },
          ],
          flashcards: [
            { q: "Nullité absolue : qui peut agir ? confirmation ?", a: "Toute personne justifiant d'un intérêt et le ministère public ; pas de confirmation (art. 1180)." },
            { q: "Cass. ch. mixte, 17 mai 2013 ?", a: "Contrats concomitants ou successifs incluant une location financière = interdépendants ; clauses contraires réputées non écrites." },
          ],
        },
      ],
    },
    {
      id: "effets",
      title: "Les effets et l'inexécution du contrat",
      level: 2,
      summary: "Force obligatoire et imprévision, tiers, sanctions de l'inexécution, clauses des contrats d'affaires.",
      lessons: [
        {
          id: "force-obligatoire-imprevision",
          title: "Force obligatoire, interprétation, durée et imprévision",
          duration: 20,
          src: P + "force-obligatoire-imprevision.md",
          objectives: ["Appliquer les règles d'interprétation", "Maîtriser la durée du contrat", "Mettre en œuvre l'article 1195"],
          keyRefs: ["Art. 1103 C. civ.", "Art. 1188 C. civ.", "Art. 1190 C. civ.", "Art. 1195 C. civ.", "Art. 1210 à 1215 C. civ.", "Art. L. 211-40-1 CMF"],
          quiz: [
            { type: "qcm", q: "Que produit la tacite reconduction ?", choices: ["La prorogation du même contrat", "Un nouveau contrat, à durée indéterminée en principe", "La nullité", "Un contrat à durée déterminée identique"], answer: 1, explain: "Art. 1215 renvoyant à 1214 : nouveau contrat identique mais à durée indéterminée." },
            { type: "vf", q: "L'art. 1195 est d'ordre public.", answer: false, explain: "Il est supplétif : les parties peuvent l'aménager ou l'écarter." },
            { type: "qcm", q: "Pendant la renégociation pour imprévision :", choices: ["L'exécution est suspendue", "La partie continue à exécuter ses obligations", "Le contrat est résolu", "Le juge fixe un nouveau prix"], answer: 1, explain: "Art. 1195 al. 1 in fine." },
            { type: "qcm", q: "Dans le doute, le contrat d'adhésion s'interprète :", choices: ["En faveur de celui qui l'a proposé", "Contre celui qui l'a proposé", "En faveur du créancier", "Selon les usages"], answer: 1, explain: "Art. 1190." },
            { type: "qcm", q: "L'imprévision est exclue légalement pour :", choices: ["Les baux commerciaux", "Les opérations sur titres et contrats financiers", "Les contrats de travail", "Les contrats d'adhésion"], answer: 1, explain: "Art. L. 211-40-1 CMF (loi de ratification de 2018)." },
          ],
          flashcards: [
            { q: "Conditions de l'imprévision (1195) ?", a: "Changement de circonstances imprévisible à la conclusion ; exécution excessivement onéreuse ; risque non accepté par la partie." },
            { q: "Canal de Craponne / Gaz de Bordeaux ?", a: "Civ., 6 mars 1876 : refus de la révision judiciaire ; CE, 30 mars 1916 : indemnité d'imprévision en droit administratif." },
            { q: "CDI : comment en sortir ?", a: "Résiliation unilatérale à tout moment, avec un préavis raisonnable (art. 1211) — et préavis L. 442-1 II en cas de relation commerciale établie." },
          ],
        },
        {
          id: "effet-relatif-tiers",
          title: "Le contrat et les tiers",
          duration: 14,
          src: P + "effet-relatif-tiers.md",
          objectives: ["Distinguer effet relatif et opposabilité", "Utiliser porte-fort et stipulation pour autrui", "Situer la jurisprudence Boot shop / Bois Rouge"],
          keyRefs: ["Art. 1199 C. civ.", "Art. 1200 C. civ.", "Art. 1204 C. civ.", "Art. 1205 C. civ."],
          quiz: [
            { type: "vf", q: "Le tiers victime d'un manquement contractuel doit prouver une faute délictuelle distincte.", answer: false, explain: "Ass. plén., 6 oct. 2006 et 13 janv. 2020 : le manquement suffit s'il a causé le dommage." },
            { type: "qcm", q: "Le maître de l'ouvrage agit contre le sous-traitant sur le fondement :", choices: ["Contractuel", "Délictuel", "Quasi-contractuel", "Il ne peut pas agir"], answer: 1, explain: "Ass. plén., 12 juill. 1991, Besse : chaîne non translative." },
            { type: "qcm", q: "Le porte-fort d'exécution garantissant un paiement risque d'être requalifié en :", choices: ["Stipulation pour autrui", "Cautionnement", "Délégation", "Novation"], answer: 1, explain: "Il faut alors respecter le régime du cautionnement." },
          ],
          flashcards: [
            { q: "Bois Rouge (Ass. plén., 13 janv. 2020) ?", a: "Le tiers qui établit un lien de causalité entre un manquement contractuel et son dommage n'a pas à prouver une faute distincte." },
          ],
        },
        {
          id: "inexecution-sanctions",
          title: "L'inexécution : les cinq sanctions et la force majeure",
          duration: 22,
          src: P + "inexecution-sanctions.md",
          objectives: ["Choisir la sanction adaptée", "Mettre en œuvre la résolution par notification", "Distinguer force majeure et imprévision"],
          keyRefs: ["Art. 1217 C. civ.", "Art. 1219 et 1220 C. civ.", "Art. 1221 et 1222 C. civ.", "Art. 1223 C. civ.", "Art. 1224 à 1230 C. civ.", "Art. 1231 à 1231-7 C. civ.", "Art. 1218 C. civ."],
          quiz: [
            { type: "qcm", q: "L'exécution forcée en nature peut être refusée :", choices: ["Pour toute obligation de faire", "En cas d'impossibilité ou de disproportion manifeste entre son coût pour le débiteur de bonne foi et son intérêt pour le créancier", "Si le débiteur le souhaite", "Jamais"], answer: 1, explain: "Art. 1221." },
            { type: "qcm", q: "La résolution par notification suppose :", choices: ["Une clause résolutoire", "Une inexécution suffisamment grave, en principe une mise en demeure, et se fait aux risques du créancier", "Une décision de justice", "L'accord du débiteur"], answer: 1, explain: "Art. 1226." },
            { type: "vf", q: "Le débiteur d'une somme d'argent peut invoquer la force majeure.", answer: false, explain: "Cass. com., 16 sept. 2014." },
            { type: "qcm", q: "Les dommages-intérêts contractuels sont limités au préjudice prévisible sauf :", choices: ["Mise en demeure", "Faute lourde ou dolosive", "Contrat d'adhésion", "Clause pénale"], answer: 1, explain: "Art. 1231-3." },
            { type: "qcm", q: "La réduction du prix (art. 1223) concerne :", choices: ["L'inexécution totale", "L'exécution imparfaite acceptée par le créancier", "L'imprévision", "La lésion"], answer: 1, explain: "Réduction proportionnelle, après mise en demeure." },
            { type: "vf", q: "Une clause de confidentialité peut survivre à la résolution du contrat.", answer: true, explain: "Art. 1230." },
          ],
          flashcards: [
            { q: "Les cinq sanctions de l'art. 1217 ?", a: "Exception d'inexécution ; exécution forcée en nature ; réduction du prix ; résolution ; dommages-intérêts (cumulables si compatibles)." },
            { q: "Critères de la force majeure contractuelle ?", a: "Événement échappant au contrôle du débiteur, imprévisible lors de la conclusion, effets inévitables (art. 1218)." },
            { q: "Exception d'inexécution anticipée ?", a: "Art. 1220 : suspension s'il est manifeste que le cocontractant ne s'exécutera pas et que les conséquences sont graves ; notification dans les meilleurs délais." },
          ],
          exercises: [
            {
              id: "cas-prestataire-informatique",
              type: "cas-pratique",
              title: "Cas pratique : le prestataire informatique défaillant",
              timerMin: 60,
              statement: `En janvier 2024, la société Logis+ (PME de logistique) confie à la société DevPro le développement d'un logiciel de gestion d'entrepôt pour 120 000 € HT, livraison prévue le 30 septembre 2024. Le contrat, rédigé par DevPro sur son modèle standard, stipule : « la responsabilité de DevPro, pour quelque cause que ce soit, est limitée à 2 000 € ».

Le 30 septembre 2024, DevPro livre une version incomplète : deux modules sur cinq ne fonctionnent pas. Logis+ a déjà payé 80 000 €. DevPro annonce qu'il lui faudra « au moins six mois de plus » et ne répond plus aux relances.

Logis+ vous demande : 1) Peut-elle cesser de payer ? 2) Peut-elle mettre fin au contrat sans attendre un jugement et confier l'achèvement à un autre prestataire ? 3) Pourra-t-elle obtenir réparation au-delà de 2 000 € ?`,
              hints: ["Contrat conclu en 2024 : droit issu de 2016.", "Pensez aux art. 1219-1220, 1226, 1222, 1170 et 1171."],
              rubric: [
                "Exception d'inexécution (art. 1219) : gravité de l'inexécution",
                "Résolution par notification (art. 1226) : mise en demeure, gravité, notification motivée, risques",
                "Faire exécuter par un tiers (art. 1222) et/ou réduction du prix (art. 1223)",
                "Restitutions après résolution (art. 1229)",
                "Clause limitative : art. 1170 (obligation essentielle), art. 1171 (contrat d'adhésion), faute lourde (art. 1231-3)",
                "Conclusions pratiques",
              ],
              model: `**1. Suspension des paiements** — Exception d'inexécution (art. 1219) : l'inexécution (deux modules sur cinq, retard annoncé de six mois) est suffisamment grave ; Logis+ peut refuser de payer le solde. Prudence : la mesure doit rester proportionnée.

**2. Mettre fin au contrat** — Résolution par notification (art. 1226) : mise en demeure préalable de s'exécuter dans un délai raisonnable, mentionnant expressément qu'à défaut Logis+ sera en droit de résoudre le contrat ; puis notification motivée. Risque : si DevPro conteste, Logis+ devra prouver la gravité de l'inexécution. Alternative : faire achever par un tiers aux frais de DevPro (art. 1222), après mise en demeure, dans un délai et à un coût raisonnables. Résolution → restitutions (art. 1229) : les prestations n'ayant d'utilité que par l'exécution complète, Logis+ peut demander la restitution des 80 000 € (sous déduction éventuelle de la valeur des modules utilisables, ou résiliation partielle).

**3. La clause limitative de 2 000 €** — (a) Art. 1170 : un plafond de 2 000 € pour un contrat de 120 000 € dont l'obligation essentielle est la livraison d'un logiciel fonctionnel peut être jugé comme privant cette obligation de sa substance (Chronopost, Faurecia) → réputé non écrit. (b) Art. 1171 : contrat rédigé sur le modèle standard de DevPro, probablement d'adhésion, clause non négociée créant un déséquilibre significatif → réputée non écrite. (c) Faute lourde (art. 1231-3) si le comportement de DevPro (abandon, silence) confine au dol. Logis+ pourra alors obtenir réparation du préjudice prévisible (surcoût du nouveau prestataire, pertes d'exploitation prouvées).

**Recommandations** : mise en demeure immédiate (LRAR), constat des dysfonctionnements (expertise, éventuellement mesure d'instruction in futurum, art. 145 CPC), devis d'un prestataire de remplacement.`,
            },
          ],
        },
        {
          id: "clauses-contrats-affaires",
          title: "Les clauses des contrats d'affaires : limitation, pénalité, hardship, juridiction",
          duration: 16,
          src: P + "clauses-contrats-affaires.md",
          objectives: ["Vérifier la validité d'une clause limitative", "Connaître le régime des clauses usuelles", "Rédiger une clause robuste"],
          keyRefs: ["Art. 1170 C. civ.", "Art. 1171 C. civ.", "Art. 1231-3 C. civ.", "Art. 1231-5 C. civ.", "Art. L. 442-1 C. com.", "Art. 48 CPC", "Art. 2061 C. civ."],
          quiz: [
            { type: "vf", q: "La faute lourde se déduit du seul manquement à une obligation essentielle.", answer: false, explain: "Ch. mixte, 22 avr. 2005 : elle se déduit de la gravité du comportement." },
            { type: "qcm", q: "Une clause attributive de compétence territoriale est valable :", choices: ["Entre toutes personnes", "Entre personnes ayant toutes contracté en qualité de commerçant, si elle est très apparente", "Seulement en arbitrage", "Jamais"], answer: 1, explain: "Art. 48 CPC." },
            { type: "qcm", q: "Une clause pénale manifestement excessive :", choices: ["Est nulle", "Peut être modérée par le juge, même d'office", "S'applique toujours", "Est réputée non écrite"], answer: 1, explain: "Art. 1231-5." },
            { type: "qcm", q: "Durée maximale d'une clause d'exclusivité d'achat (art. L. 330-1 C. com.) :", choices: ["3 ans", "5 ans", "10 ans", "Illimitée"], answer: 2, explain: "Dix ans." },
          ],
          flashcards: [
            { q: "Cinq limites aux clauses limitatives ?", a: "Faute lourde/dolosive ; obligation essentielle (1170) ; contrat d'adhésion (1171) ; L. 442-1 I 2° C. com. ; clauses abusives conso (L. 212-1, R. 212-1)." },
          ],
        },
      ],
    },
    {
      id: "regime",
      title: "Régime général, prescription et preuve",
      level: 3,
      summary: "Opérations sur obligations, extinction, prescription, preuve (y compris la preuve déloyale).",
      lessons: [
        {
          id: "operations-obligations",
          title: "Cession de créance, de dette et de contrat ; subrogation ; délégation",
          duration: 18,
          src: P + "operations-obligations.md",
          objectives: ["Céder une créance sans formalisme excessif", "Organiser une cession de contrat", "Utiliser subrogation et délégation"],
          keyRefs: ["Art. 1216 C. civ.", "Art. 1321 à 1326 C. civ.", "Art. 1327 C. civ.", "Art. 1346 C. civ.", "Art. 1336 C. civ.", "Art. L. 313-23 CMF"],
          quiz: [
            { type: "qcm", q: "La cession de créance est opposable aux tiers :", choices: ["Après signification par commissaire de justice", "Dès la date de l'acte", "Après publication", "Après acceptation du débiteur"], answer: 1, explain: "Art. 1323 ; l'ancien art. 1690 a disparu." },
            { type: "qcm", q: "Pour être opposable au débiteur cédé, la cession doit :", choices: ["Être publiée", "Lui être notifiée ou qu'il en ait pris acte", "Être authentique", "Rien"], answer: 1, explain: "Art. 1324." },
            { type: "vf", q: "La cession de contrat requiert l'accord du cocontractant cédé, qui peut être donné par avance.", answer: true, explain: "Art. 1216." },
            { type: "qcm", q: "En l'absence de libération expresse par le créancier, le cédant d'une dette :", choices: ["Est libéré", "Reste solidairement tenu", "Devient caution", "Est subrogé"], answer: 1, explain: "Art. 1327-2." },
            { type: "vf", q: "La subrogation légale est désormais générale au profit de celui qui paie avec un intérêt légitime.", answer: true, explain: "Art. 1346." },
          ],
          flashcards: [
            { q: "Forme de la cession de créance ?", a: "Écrit à peine de nullité (art. 1322)." },
            { q: "Délégation : principe protecteur du délégataire ?", a: "Inopposabilité des exceptions du délégué tirées de ses rapports avec le délégant (art. 1336)." },
          ],
        },
        {
          id: "extinction-prescription-preuve",
          title: "Paiement, compensation, prescription et preuve",
          duration: 20,
          src: P + "extinction-prescription-preuve.md",
          objectives: ["Calculer une prescription", "Interrompre ou suspendre un délai", "Prouver un acte et apprécier une preuve déloyale"],
          keyRefs: ["Art. 1343-2 C. civ.", "Art. 1347 C. civ.", "Art. 1348-1 C. civ.", "Art. 2224 C. civ.", "Art. 2232 C. civ.", "Art. 2240 à 2246 C. civ.", "Art. L. 110-4 C. com.", "Art. 1359 C. civ.", "Art. L. 110-3 C. com."],
          quiz: [
            { type: "qcm", q: "Prescription des obligations entre commerçants :", choices: ["10 ans", "5 ans", "2 ans", "30 ans"], answer: 1, explain: "Art. L. 110-4 C. com., depuis la loi du 17 juin 2008." },
            { type: "qcm", q: "Une assignation en référé :", choices: ["N'a aucun effet sur la prescription", "Interrompt la prescription", "Suspend la prescription", "Fait courir un délai de 2 ans"], answer: 1, explain: "Art. 2241 : la demande en justice, même en référé, interrompt." },
            { type: "qcm", q: "Délai butoir de droit commun :", choices: ["10 ans", "20 ans", "30 ans", "Il n'en existe pas"], answer: 1, explain: "Art. 2232 : 20 ans à compter de la naissance du droit." },
            { type: "vf", q: "Depuis 2023, une preuve obtenue de manière déloyale est toujours irrecevable en matière civile.", answer: false, explain: "Ass. plén., 22 déc. 2023 : recevable si indispensable et l'atteinte strictement proportionnée." },
            { type: "qcm", q: "Contre un commerçant, un acte de commerce se prouve :", choices: ["Par écrit au-delà de 1 500 €", "Par tous moyens", "Par acte authentique", "Par témoins uniquement"], answer: 1, explain: "Art. L. 110-3 C. com." },
          ],
          flashcards: [
            { q: "Point de départ de la prescription de droit commun ?", a: "Jour où le titulaire a connu ou aurait dû connaître les faits lui permettant d'exercer son droit (art. 2224)." },
            { q: "Ass. plén., 22 déc. 2023 ?", a: "Preuve illicite ou déloyale non systématiquement écartée : contrôle de proportionnalité (indispensable, atteinte strictement proportionnée)." },
            { q: "Compensation de dettes connexes en procédure collective ?", a: "Possible après le jugement d'ouverture (art. L. 622-7 C. com. ; art. 1348-1 C. civ.)." },
          ],
        },
      ],
    },
  ],
  decisions: [
    { id: "craponne", name: "Canal de Craponne", court: "Cass. civ.", date: "6 mars 1876", topic: "Imprévision", solution: "Le juge ne peut, quelque équitable que puisse lui paraître sa décision, modifier les conventions des parties pour tenir compte du temps et des circonstances.", scope: "Refus de la révision pour imprévision en droit privé pendant 140 ans.", status: "abandonné", statusNote: "Écarté par l'art. 1195 C. civ. pour les contrats conclus depuis le 1er octobre 2016 (règle supplétive)." },
    { id: "chronopost", name: "Chronopost", court: "Cass. com.", date: "22 octobre 1996", number: "n° 93-18.632", topic: "Clause limitative et obligation essentielle", solution: "La clause limitative de responsabilité qui contredit la portée de l'engagement essentiel (livraison dans un délai garanti) est réputée non écrite.", scope: "Contrôle des clauses par la cause, puis par l'obligation essentielle.", status: "codifié", statusNote: "Art. 1170 C. civ." },
    { id: "faurecia-2", name: "Faurecia II", court: "Cass. com.", date: "29 juin 2010", number: "n° 09-11.841", topic: "Clause limitative et obligation essentielle", solution: "Seule est réputée non écrite la clause limitative qui contredit la portée de l'obligation essentielle ; un plafond non dérisoire est valable.", scope: "Appréciation concrète au regard de l'économie du contrat.", status: "codifié", statusNote: "Art. 1170 C. civ., appliqué dans le même esprit." },
    { id: "chronopost-mixte", name: "Chronopost (chambre mixte)", court: "Cass. ch. mixte", date: "22 avril 2005", topic: "Faute lourde", solution: "La faute lourde ne peut résulter du seul manquement à une obligation contractuelle, fût-elle essentielle, mais doit se déduire de la gravité du comportement du débiteur.", scope: "Définition subjective de la faute lourde.", status: "en vigueur" },
    { id: "pourparlers-manoukian", name: "Manoukian", court: "Cass. com.", date: "26 novembre 2003", number: "n° 00-10.243", topic: "Rupture des pourparlers", solution: "La faute commise dans la rupture des pourparlers n'est pas la cause du préjudice consistant dans la perte de chance de réaliser les gains espérés du contrat.", scope: "Limitation du préjudice réparable.", status: "codifié", statusNote: "Art. 1112 al. 2, étendu en 2018 à la perte de chance." },
    { id: "baldus", name: "Baldus", court: "Cass. civ. 1re", date: "3 mai 2000", number: "n° 98-11.381", topic: "Réticence dolosive, valeur", solution: "Aucune obligation d'information ne pèse sur l'acheteur quant à la valeur du bien.", scope: "Pas de devoir d'information sur l'estimation de la valeur.", status: "codifié", statusNote: "Art. 1112-1 al. 2 et 1137 al. 3." },
    { id: "vilgrain", name: "Vilgrain", court: "Cass. com.", date: "27 février 1996", number: "n° 94-11.241", topic: "Devoir de loyauté du dirigeant", solution: "Manque à son devoir de loyauté et commet une réticence dolosive le dirigeant qui acquiert les titres d'un associé en lui dissimulant une négociation de revente plus avantageuse.", scope: "Devoir de loyauté du dirigeant envers les associés.", status: "en vigueur" },
    { id: "cruz", name: "Consorts Cruz", court: "Cass. civ. 3e", date: "15 décembre 1993", topic: "Promesse unilatérale", solution: "La rétractation du promettant avant la levée de l'option exclut la formation du contrat ; seuls des dommages-intérêts sont dus.", scope: "Promesse unilatérale privée d'efficacité.", status: "abandonné", statusNote: "Art. 1124 al. 2 et revirement Civ. 3e, 23 juin 2021, n° 20-17.554." },
    { id: "promesse-2021", name: "Revirement sur la promesse unilatérale", court: "Cass. civ. 3e", date: "23 juin 2021", number: "n° 20-17.554", topic: "Promesse unilatérale", solution: "La rétractation du promettant pendant le délai d'option n'empêche pas la formation du contrat promis ; exécution forcée possible.", scope: "Aligne l'ancien droit sur l'art. 1124.", status: "en vigueur" },
    { id: "pacte-preference-2006", name: "Pacte de préférence (chambre mixte)", court: "Cass. ch. mixte", date: "26 mai 2006", topic: "Pacte de préférence", solution: "Le bénéficiaire peut obtenir l'annulation du contrat passé avec un tiers et sa substitution si le tiers connaissait le pacte et l'intention du bénéficiaire de s'en prévaloir.", scope: "Sanction en nature du pacte.", status: "codifié", statusNote: "Art. 1123 al. 2." },
    { id: "prix-1995", name: "Indétermination du prix", court: "Cass. ass. plén.", date: "1er décembre 1995", topic: "Prix dans les contrats-cadres", solution: "L'indétermination du prix des contrats d'application n'affecte pas la validité du contrat-cadre ; l'abus dans la fixation du prix donne lieu à résiliation ou indemnisation.", scope: "Fin des annulations de contrats de distribution pour indétermination du prix.", status: "codifié", statusNote: "Art. 1164 C. civ." },
    { id: "marechaux", name: "Les Maréchaux", court: "Cass. com.", date: "10 juillet 2007", number: "n° 06-14.768", topic: "Bonne foi", solution: "Si la bonne foi permet au juge de sanctionner l'usage déloyal d'une prérogative contractuelle, elle ne l'autorise pas à porter atteinte à la substance même des droits et obligations légalement convenus.", scope: "Limite du pouvoir du juge au nom de la bonne foi.", status: "en vigueur" },
    { id: "interdependance-2013", name: "Interdépendance contractuelle", court: "Cass. ch. mixte", date: "17 mai 2013", number: "n° 11-22.768", topic: "Ensembles contractuels", solution: "Les contrats concomitants ou successifs incluant une location financière sont interdépendants ; les clauses contraires sont réputées non écrites.", scope: "Caducité en cascade.", status: "codifié", statusNote: "Art. 1186 C. civ." },
    { id: "boot-shop", name: "Boot shop (Myr'Ho)", court: "Cass. ass. plén.", date: "6 octobre 2006", number: "n° 05-13.255", topic: "Tiers et manquement contractuel", solution: "Le tiers peut invoquer, sur le fondement délictuel, un manquement contractuel dès lors qu'il lui a causé un dommage.", scope: "Identité des fautes contractuelle et délictuelle.", status: "en vigueur", statusNote: "Confirmé par Ass. plén., 13 janv. 2020, Bois Rouge." },
    { id: "bois-rouge", name: "Sucrerie de Bois Rouge", court: "Cass. ass. plén.", date: "13 janvier 2020", number: "n° 17-19.963", topic: "Tiers et manquement contractuel", solution: "Le tiers qui établit un lien de causalité entre un manquement contractuel et son dommage n'a pas à démontrer une faute délictuelle distincte.", scope: "Confirmation de Boot shop.", status: "en vigueur" },
    { id: "besse", name: "Besse", court: "Cass. ass. plén.", date: "12 juillet 1991", topic: "Sous-traitance", solution: "Le sous-traitant n'est pas contractuellement lié au maître de l'ouvrage ; l'action de ce dernier est délictuelle.", scope: "Pas d'action contractuelle directe dans les chaînes non translatives.", status: "en vigueur" },
    { id: "force-majeure-argent", name: "Force majeure et somme d'argent", court: "Cass. com.", date: "16 septembre 2014", number: "n° 13-20.306", topic: "Force majeure", solution: "Le débiteur d'une obligation contractuelle de somme d'argent inexécutée ne peut s'exonérer en invoquant la force majeure.", scope: "Exclusion de la force majeure pour les dettes d'argent.", status: "en vigueur" },
    { id: "preuve-deloyale", name: "Preuve déloyale", court: "Cass. ass. plén.", date: "22 décembre 2023", number: "n° 20-20.648", topic: "Preuve", solution: "L'illicéité ou la déloyauté d'un moyen de preuve n'entraîne pas nécessairement son rejet ; le juge apprécie si sa production est indispensable et l'atteinte strictement proportionnée.", scope: "Revirement : droit à la preuve et contrôle de proportionnalité.", status: "en vigueur" },
    { id: "tocqueville", name: "Tocqueville", court: "Cass. civ. 1re", date: "13 octobre 1998", topic: "Résolution unilatérale", solution: "La gravité du comportement d'une partie peut justifier que l'autre y mette fin de façon unilatérale à ses risques et périls.", scope: "Résolution unilatérale extra-judiciaire.", status: "codifié", statusNote: "Art. 1226 C. civ. (résolution par notification)." },
  ],
  reforms: [
    { date: "2008-06-17", title: "Réforme de la prescription civile", summary: "Loi n° 2008-561 : délai de droit commun ramené de 30 à 5 ans (art. 2224), délai entre commerçants de 10 à 5 ans, délai butoir de 20 ans." },
    { date: "2016-10-01", title: "Entrée en vigueur de la réforme du droit des contrats", summary: "Ord. n° 2016-131 du 10 févr. 2016 : nouveau droit commun des contrats, régime général et preuve des obligations ; disparition de la cause ; imprévision ; clauses abusives dans les contrats d'adhésion." },
    { date: "2018-04-20", title: "Loi de ratification de la réforme des contrats", summary: "Loi n° 2018-287 : retouches (contrat d'adhésion, art. 1171, 1143, 1223…), applicables pour partie aux contrats conclus à compter du 1er octobre 2018." },
    { date: "2020-01-13", title: "Bois Rouge : le tiers et le manquement contractuel", summary: "L'assemblée plénière confirme que le tiers peut invoquer un manquement contractuel causant son dommage sans prouver de faute distincte." },
    { date: "2021-06-23", title: "Revirement sur la promesse unilatérale", summary: "Civ. 3e : la rétractation du promettant n'empêche pas la formation du contrat, même pour les promesses antérieures à 2016." },
    { date: "2023-12-22", title: "Preuve déloyale admise sous conditions", summary: "Ass. plén. : le juge met en balance le droit à la preuve et les droits antinomiques ; preuve recevable si indispensable et proportionnée." },
  ],
  glossary: [
    { term: "Contrat d'adhésion", def: "Contrat comportant un ensemble de clauses non négociables, déterminées à l'avance par l'une des parties (art. 1110)." },
    { term: "Contrat-cadre", def: "Accord par lequel les parties conviennent des caractéristiques générales de leurs relations contractuelles futures, précisées par des contrats d'application (art. 1111)." },
    { term: "Caducité", def: "Disparition d'un contrat valablement formé du fait de la disparition de l'un de ses éléments essentiels (art. 1186)." },
    { term: "Imprévision", def: "Changement de circonstances imprévisible rendant l'exécution excessivement onéreuse ; ouvre une renégociation puis une révision judiciaire (art. 1195)." },
    { term: "Réputé non écrit", def: "Sanction par laquelle une clause est censée n'avoir jamais existé, le reste du contrat étant maintenu." },
    { term: "Action interrogatoire", def: "Faculté de sommer une personne de prendre parti dans un délai (pacte de préférence, représentation, nullité : art. 1123, 1158, 1183)." },
    { term: "Porte-fort", def: "Engagement de faire ratifier un acte par un tiers ou de garantir son exécution par un tiers (art. 1203-1204)." },
    { term: "Subrogation personnelle", def: "Transmission de la créance et de ses accessoires à celui qui paie le créancier (art. 1346 s.)." },
    { term: "Délégation", def: "Opération par laquelle le délégant obtient du délégué qu'il s'oblige envers le délégataire (art. 1336)." },
    { term: "Clause pénale", def: "Clause fixant forfaitairement les dommages-intérêts dus en cas d'inexécution, révisable par le juge (art. 1231-5)." },
    { term: "Pacta sunt servanda", def: "Les conventions doivent être respectées : force obligatoire du contrat.", latin: true },
    { term: "Res inter alios acta", def: "Ce qui a été fait entre les uns ne nuit ni ne profite aux autres : effet relatif.", latin: true },
    { term: "Exceptio non adimpleti contractus", def: "Exception d'inexécution : refus d'exécuter tant que l'autre partie n'exécute pas (art. 1219).", latin: true },
    { term: "Specialia generalibus derogant", def: "Les règles spéciales dérogent aux règles générales (art. 1105).", latin: true },
    { term: "Fraus omnia corrumpit", def: "La fraude corrompt tout.", latin: true },
    { term: "Nemo auditur propriam turpitudinem allegans", def: "Nul ne peut se prévaloir de sa propre turpitude.", latin: true },
    { term: "Contra proferentem", def: "Interprétation contre celui qui a rédigé ou proposé la clause (art. 1190).", latin: true },
    { term: "Accessorium sequitur principale", def: "L'accessoire suit le principal (sûretés transmises avec la créance).", latin: true },
  ],
};
