const P = "packs/responsabilite/";

export default {
  id: "responsabilite",
  version: "2026.10.1",
  title: "Responsabilité civile et quasi-contrats",
  branch: "Droit privé",
  icon: "⚠️",
  color: "#b23b3b",
  order: 2,
  updatedAt: "2026-10-01",
  description: "Conditions de la responsabilité, fait personnel, fait des choses et d'autrui, régimes spéciaux, réparation ; enrichissement injustifié et autres quasi-contrats.",
  modules: [
    {
      id: "droit-commun",
      title: "Le droit commun de la responsabilité",
      level: 1,
      summary: "Conditions communes, faute, non-cumul ; fait des choses et fait d'autrui.",
      lessons: [
        {
          id: "conditions-fait-personnel",
          title: "Conditions de la responsabilité et fait personnel",
          duration: 15,
          src: P + "conditions-fait-personnel.md",
          objectives: ["Retrouver les nouveaux numéros", "Caractériser dommage et causalité", "Appliquer le non-cumul"],
          keyRefs: ["Art. 1240 C. civ.", "Art. 1241 C. civ.", "Art. 414-3 C. civ."],
          quiz: [
            { type: "qcm", q: "L'ancien article 1382 est devenu :", choices: ["1231-1", "1240", "1242", "1245"], answer: 1, explain: "Renumérotation de 2016, sans réforme du fond." },
            { type: "vf", q: "La réforme de la responsabilité civile extracontractuelle a été adoptée en 2016 avec celle des contrats.", answer: false, explain: "Seule une renumérotation a eu lieu ; le projet de réforme n'est pas adopté à ce jour." },
            { type: "qcm", q: "La perte de chance est réparée :", choices: ["À hauteur de l'avantage espéré", "À hauteur de la chance perdue", "Jamais", "Symboliquement"], answer: 1, explain: "Mesure de la chance perdue, jamais de l'avantage espéré." },
            { type: "vf", q: "Un enfant en bas âge peut commettre une faute civile.", answer: true, explain: "Ass. plén., 9 mai 1984 (Lemaire, Derguini) : faute objective." },
            { type: "qcm", q: "Le créancier contractuel peut-il agir sur le fondement délictuel contre son cocontractant ?", choices: ["Oui, au choix", "Non : principe de non-cumul", "Seulement en cas de faute lourde", "Seulement s'il est consommateur"], answer: 1, explain: "Principe de non-cumul (non-option)." },
          ],
          flashcards: [
            { q: "Caractères du préjudice réparable ?", a: "Certain, direct, personnel, légitime." },
            { q: "Art. 1253 C. civ. ?", a: "Trouble anormal de voisinage, codifié par la loi du 15 avril 2024." },
          ],
        },
        {
          id: "fait-choses-autrui",
          title: "Fait des choses et fait d'autrui (art. 1242)",
          duration: 16,
          src: P + "fait-choses-autrui.md",
          objectives: ["Identifier le gardien", "Engager la responsabilité du commettant", "Connaître les immunités du préposé"],
          keyRefs: ["Art. 1242 C. civ."],
          quiz: [
            { type: "qcm", q: "La garde se définit par :", choices: ["La propriété", "L'usage, la direction et le contrôle", "La possession", "L'assurance"], answer: 1, explain: "Ch. réunies, 2 déc. 1941, Franck." },
            { type: "qcm", q: "Pour une chose inerte, la victime doit prouver :", choices: ["La faute du gardien", "L'anormalité de la chose", "Rien", "La force majeure"], answer: 1, explain: "Position, état ou fonctionnement anormal." },
            { type: "qcm", q: "Le préposé qui agit sans excéder les limites de sa mission :", choices: ["Est responsable envers les tiers", "N'engage pas sa responsabilité envers les tiers", "Est solidairement tenu", "Doit rembourser le commettant"], answer: 1, explain: "Costedoat, Ass. plén., 25 févr. 2000." },
            { type: "vf", q: "Le préposé condamné pour une infraction pénale intentionnelle peut voir sa responsabilité civile engagée envers la victime, même s'il a agi sur ordre.", answer: true, explain: "Cousin, Ass. plén., 14 déc. 2001." },
          ],
          flashcards: [
            { q: "Jand'heur (1930) ?", a: "Présomption de responsabilité du gardien, détruite seulement par la cause étrangère, pas par l'absence de faute." },
            { q: "Abus de fonctions (Ass. plén., 19 mai 1988) ?", a: "Le commettant s'exonère si le préposé a agi hors de ses fonctions, sans autorisation et à des fins étrangères à ses attributions." },
          ],
        },
      ],
    },
    {
      id: "speciaux",
      title: "Régimes spéciaux et réparation",
      level: 2,
      summary: "Produits défectueux, loi Badinter, voisinage, préjudice écologique ; réparation intégrale.",
      lessons: [
        {
          id: "regimes-speciaux-reparation",
          title: "Régimes spéciaux et réparation du préjudice",
          duration: 18,
          src: P + "regimes-speciaux-reparation.md",
          objectives: ["Appliquer le régime des produits défectueux", "Connaître la loi Badinter", "Évaluer un préjudice économique"],
          keyRefs: ["Art. 1245 à 1245-17 C. civ.", "Art. 1246 à 1252 C. civ.", "Art. 1253 C. civ.", "Loi n° 85-677 du 5 juill. 1985"],
          quiz: [
            { type: "qcm", q: "Le risque de développement est :", choices: ["Une cause d'exonération du producteur", "Une circonstance aggravante", "Un préjudice réparable", "Une notion de droit des sociétés"], answer: 0, explain: "Art. 1245-10, sauf pour les éléments du corps humain." },
            { type: "qcm", q: "Délai d'extinction de la responsabilité du producteur :", choices: ["3 ans après la mise en circulation", "10 ans après la mise en circulation", "20 ans", "5 ans"], answer: 1, explain: "Dix ans, sauf action engagée ; l'action elle-même se prescrit par 3 ans." },
            { type: "vf", q: "En droit français, la victime a l'obligation de minimiser son dommage.", answer: false, explain: "Civ. 2e, 19 juin 2003." },
            { type: "qcm", q: "Le préjudice écologique se répare :", choices: ["Exclusivement en argent", "Par priorité en nature", "Par une amende pénale", "Il n'est pas réparable"], answer: 1, explain: "Art. 1249." },
          ],
          flashcards: [
            { q: "Défaut d'un produit ?", a: "N'offre pas la sécurité à laquelle on peut légitimement s'attendre (art. 1245-3)." },
            { q: "Réparation intégrale ?", a: "Tout le préjudice, rien que le préjudice ; pas de dommages-intérêts punitifs." },
          ],
        },
        {
          id: "quasi-contrats",
          title: "Les quasi-contrats : gestion d'affaires, paiement de l'indu, enrichissement injustifié",
          objectives: ["Distinguer les trois quasi-contrats codifiés en 2016", "Maîtriser la subsidiarité de l'enrichissement injustifié"],
          outline: [
            "Notion et place des quasi-contrats (art. 1300)",
            "La gestion d'affaires (art. 1301 à 1301-5)",
            "Le paiement de l'indu (art. 1302 à 1302-3)",
            "L'enrichissement injustifié (art. 1303 à 1303-4) : conditions, subsidiarité, indemnisation",
            "Applications en droit des affaires",
          ],
          keyRefs: ["Art. 1300 C. civ.", "Art. 1301 C. civ.", "Art. 1302 C. civ.", "Art. 1303 C. civ."],
        },
        {
          id: "responsabilite-reforme",
          title: "Le projet de réforme de la responsabilité civile : état des lieux",
          level: 3,
          objectives: ["Connaître les principales innovations envisagées", "Mesurer l'état d'avancement du projet"],
          outline: [
            "Historique : avant-projet de 2016, projet de 2017, proposition de loi sénatoriale de 2020",
            "Principales innovations : préjudice corporel, non-cumul, tiers victime d'un manquement contractuel, amende civile, obligation de minimiser",
            "État actuel des travaux législatifs",
            "Conséquences pratiques pour les entreprises",
          ],
        },
      ],
    },
  ],
  decisions: [
    { id: "teffaine", name: "Teffaine", court: "Cass. civ.", date: "16 juin 1896", topic: "Fait des choses", solution: "Découverte d'un principe de responsabilité du fait des choses fondé sur l'article 1384 al. 1 (explosion d'une chaudière).", scope: "Naissance de la responsabilité du fait des choses.", status: "en vigueur", statusNote: "Art. 1242 al. 1." },
    { id: "jandheur", name: "Jand'heur", court: "Cass. ch. réunies", date: "13 février 1930", topic: "Fait des choses", solution: "La présomption pesant sur le gardien n'est détruite que par la preuve d'une cause étrangère, non par l'absence de faute.", scope: "Responsabilité de plein droit du gardien.", status: "en vigueur" },
    { id: "franck", name: "Franck", court: "Cass. ch. réunies", date: "2 décembre 1941", topic: "Garde", solution: "Le propriétaire privé de l'usage, de la direction et du contrôle de sa chose (vol) n'en a plus la garde.", scope: "Définition de la garde.", status: "en vigueur" },
    { id: "blieck", name: "Blieck", court: "Cass. ass. plén.", date: "29 mars 1991", topic: "Fait d'autrui", solution: "L'association qui organise et contrôle à titre permanent le mode de vie d'un handicapé répond de ses actes sur le fondement de l'art. 1384 al. 1.", scope: "Principe général de responsabilité du fait d'autrui.", status: "en vigueur" },
    { id: "costedoat", name: "Costedoat", court: "Cass. ass. plén.", date: "25 février 2000", topic: "Commettant / préposé", solution: "Le préposé qui agit sans excéder les limites de sa mission n'engage pas sa responsabilité envers les tiers.", scope: "Immunité du préposé.", status: "en vigueur" },
    { id: "cousin", name: "Cousin", court: "Cass. ass. plén.", date: "14 décembre 2001", topic: "Commettant / préposé", solution: "Le préposé condamné pour une infraction pénale intentionnelle, même commise sur ordre, engage sa responsabilité civile envers la victime.", scope: "Limite à l'immunité Costedoat.", status: "en vigueur" },
    { id: "lemaire-derguini", name: "Lemaire et Derguini", court: "Cass. ass. plén.", date: "9 mai 1984", topic: "Faute de l'enfant", solution: "La faute d'un jeune enfant peut être retenue sans qu'il soit nécessaire de vérifier s'il était capable de discerner les conséquences de ses actes.", scope: "Faute objective.", status: "en vigueur" },
    { id: "bertrand", name: "Bertrand", court: "Cass. civ. 2e", date: "19 février 1997", topic: "Responsabilité des parents", solution: "Seule la force majeure ou la faute de la victime exonère les parents de leur responsabilité de plein droit.", scope: "Responsabilité objective des parents.", status: "en vigueur" },
    { id: "minimiser", name: "Absence d'obligation de minimiser", court: "Cass. civ. 2e", date: "19 juin 2003", topic: "Réparation", solution: "L'auteur d'un accident doit en réparer toutes les conséquences dommageables ; la victime n'est pas tenue de limiter son préjudice dans l'intérêt du responsable.", scope: "Réparation intégrale sans obligation de minimisation.", status: "en vigueur" },
  ],
  reforms: [
    { date: "2016-08-08", title: "Préjudice écologique dans le Code civil", summary: "Loi pour la reconquête de la biodiversité : art. 1246 à 1252 C. civ., réparation par priorité en nature." },
    { date: "2024-04-15", title: "Codification du trouble anormal de voisinage", summary: "Loi n° 2024-346 : art. 1253 C. civ., responsabilité de plein droit et exception d'antériorité." },
    { date: "2024-11-18", title: "Nouvelle directive « produits défectueux »", summary: "Directive (UE) 2024/2853 : extension aux logiciels et à l'IA, allègement de la preuve ; transposition attendue d'ici décembre 2026." },
  ],
  glossary: [
    { term: "Garde", def: "Pouvoir d'usage, de direction et de contrôle d'une chose (arrêt Franck)." },
    { term: "Préposé", def: "Personne qui agit pour le compte et sous l'autorité d'un commettant." },
    { term: "Perte de chance", def: "Disparition actuelle et certaine d'une éventualité favorable, réparée à hauteur de la chance perdue." },
    { term: "Préjudice par ricochet", def: "Préjudice subi par un proche de la victime directe." },
    { term: "Nomenclature Dintilhac", def: "Liste des postes de préjudice corporel établie en 2005, référence des juridictions." },
    { term: "Damnum emergens", def: "Perte subie.", latin: true },
    { term: "Lucrum cessans", def: "Gain manqué.", latin: true },
    { term: "Neminem laedere", def: "Ne nuire à personne : fondement du devoir général de prudence.", latin: true },
  ],
};
